SELECT
  DEPARTAMENTO.NOME AS "Departamento",
  EMPREGADO.NOME AS "Empregado",
  COALESCE(ROUND(SUM(VENCIMENTO.VALOR), 2), 0) AS "Salario Bruto",
  COALESCE(ROUND(TABELA.VAL_DESC, 2), 0) AS "Total Desconto",
  COALESCE(ROUND(SUM(VENCIMENTO.VALOR) - (COALESCE(TABELA.VAL_DESC, 0)), 2), 0) AS "Salario Liquidoaws"
FROM
  EMP_VENC
  RIGHT JOIN EMPREGADO ON EMPREGADO.MATR = EMP_VENC.MATR
  LEFT JOIN VENCIMENTO ON VENCIMENTO.COD_VENC = EMP_VENC.COD_VENC
  LEFT JOIN DEPARTAMENTO ON DEPARTAMENTO.COD_DEP = EMPREGADO.LOTACAO
  LEFT JOIN (
    SELECT
      EMPREGADO.MATR,
      SUM(DESCONTO.VALOR) AS VAL_DESC
    FROM
      EMPREGADO
      INNER JOIN EMP_DESC ON EMP_DESC.MATR = EMPREGADO.MATR
      LEFT JOIN DESCONTO ON DESCONTO.COD_DESC = EMP_DESC.COD_DESC
    GROUP BY
      EMPREGADO.MATR
  ) AS TABELA ON TABELA.MATR = EMPREGADO.MATR
GROUP BY
  DEPARTAMENTO.NOME,
  EMPREGADO.NOME,
  TABELA.VAL_DESC
ORDER BY
  (
    COALESCE(SUM(VENCIMENTO.VALOR), 0) - COALESCE(TABELA.VAL_DESC, 0)
  ) DESC
